### ISSUE TITLE
'/about' Page updates

### ISSUE THREAD

**Issue by kswrestlingcenter1** [kswrestlingcenter/kwc#12]
# `/about`

### http://www.kswrestlingcenter.com/about

- [x] Fix Carousel.
- [x] Pictures to add

---

![123600586_116793956874664_5301136409400116383_n](https://user-images.githubusercontent.com/73113073/103420070-3c420980-4b5b-11eb-9436-582c0314aec3.jpg)

---

![129407685_124466399440753_4285616585985583995_n](https://user-images.githubusercontent.com/73113073/103420072-3cdaa000-4b5b-11eb-826f-00246d184e46.jpg)

---

![129585102_124466349440758_6396210294773054925_n](https://user-images.githubusercontent.com/73113073/103420073-3cdaa000-4b5b-11eb-9c03-c238eaf59856.jpg)

---

![Screen Shot 2020-12-29 at 6 50 42 AM](https://user-images.githubusercontent.com/73113073/103420074-3d733680-4b5b-11eb-8540-bc23c011f98b.png)

**Comment by AldonIsenberg11** [comment]
done
